apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: muchtodo-ns
data:
  PORT: "3000"
  MONGO_URI: "mongodb://root:example@mongodb:27017"
  DB_NAME: "much_todo_db"
  JWT_EXPIRATION_HOURS: "72"
  ENABLE_CACHE: "false"
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  SECURE_COOKIE: "false"
  ALLOWED_ORIGINS: "http://localhost:5173"
