apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: muchtodo-ns
type: Opaque
data:
  # your-secret-key-change-in-production
  JWT_SECRET_KEY: eW91ci1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9u
